/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSchedulesRouteImport } from './routes/_shell.schedules'
import { Route as ShellKnowledgeBaseRouteImport } from './routes/_shell.knowledge-base'
import { Route as ShellHistoryRouteImport } from './routes/_shell.history'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellAgentsRouteImport } from './routes/_shell.agents'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulesRoute = ShellSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeBaseRoute = ShellKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHistoryRoute = ShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/agents': typeof ShellAgentsRoute
  '/help': typeof ShellHelpRoute
  '/history': typeof ShellHistoryRoute
  '/knowledge-base': typeof ShellKnowledgeBaseRoute
  '/schedules': typeof ShellSchedulesRoute
  '/settings': typeof ShellSettingsRoute
  '/agents/$id': typeof AgentsIdRoute
}
export interface FileRoutesByTo {
  '/agents': typeof ShellAgentsRoute
  '/help': typeof ShellHelpRoute
  '/history': typeof ShellHistoryRoute
  '/knowledge-base': typeof ShellKnowledgeBaseRoute
  '/schedules': typeof ShellSchedulesRoute
  '/settings': typeof ShellSettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/agents': typeof ShellAgentsRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/history': typeof ShellHistoryRoute
  '/_shell/knowledge-base': typeof ShellKnowledgeBaseRoute
  '/_shell/schedules': typeof ShellSchedulesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/help'
    | '/history'
    | '/knowledge-base'
    | '/schedules'
    | '/settings'
    | '/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/help'
    | '/history'
    | '/knowledge-base'
    | '/schedules'
    | '/settings'
    | '/agents/$id'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/agents'
    | '/_shell/help'
    | '/_shell/history'
    | '/_shell/knowledge-base'
    | '/_shell/schedules'
    | '/_shell/settings'
    | '/agents/$id'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AgentsIdRoute: typeof AgentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedules': {
      id: '/_shell/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof ShellSchedulesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge-base': {
      id: '/_shell/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof ShellKnowledgeBaseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/history': {
      id: '/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ShellHistoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAgentsRoute: typeof ShellAgentsRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellHistoryRoute: typeof ShellHistoryRoute
  ShellKnowledgeBaseRoute: typeof ShellKnowledgeBaseRoute
  ShellSchedulesRoute: typeof ShellSchedulesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgentsRoute: ShellAgentsRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellHistoryRoute: ShellHistoryRoute,
  ShellKnowledgeBaseRoute: ShellKnowledgeBaseRoute,
  ShellSchedulesRoute: ShellSchedulesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AgentsIdRoute: AgentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
